#
# Executes commands at the start of an interactive session.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#

# Source Prezto.
if [[ -s "${ZDOTDIR:-$HOME}/git/dotfiles/.zprezto/init.zsh" ]]; then
  source "${ZDOTDIR:-$HOME}/git/dotfiles/.zprezto/init.zsh"
fi

### Exports
export JAVA_HOME=`/usr/libexec/java_home -v "10"`

export ZPLG_HOME="${ZDOTDIR:-$HOME}/.zplugin"

export ANDROID_HOME="$HOME/Library/Android/sdk"
export PATH=$ANDROID_HOME/platform-tools:$PATH

export GOPATH=$HOME/.go
export GOROOT=$( go env GOROOT )
export PATH=$GOPATH/bin:$PATH

### Zplugin
source "$ZPLG_HOME/bin/zplugin.zsh"
autoload -Uz _zplugin
(( ${+_comps} )) && _comps[zplugin]=_zplugin

zplugin light zsh-users/zsh-autosuggestions
zplugin light zsh-users/zsh-syntax-highlighting

autoload -Uz compinit
compinit
