[[plugins]]
 repo = 'Shougo/dein.vim'

[[plugins]]
repo = 'Shougo/deoplete.nvim'
hook_add = 'let g:deoplete#enable_at_startup = 1'

[[plugins]]
repo = 'junegunn/fzf'
build = './install --bin'
merged = '0'

[[plugins]]
repo = 'junegunn/fzf.vim'
depend = 'fzf'

[[plugins]]
repo = 'scrooloose/nerdtree'

[[plugins]]
repo = 'whatyouhide/vim-gotham'

[[plugins]]
repo = 'itchyny/lightline.vim'
hook_add = '''
  let g:lightline = {'colorscheme': 'one'}
	set laststatus=2
	set noshowmode
'''

